"""Add tickets tables

Revision ID: 20767b912bb1
Revises: 454f3680cbb9
Create Date: 2025-05-03 01:15:53.407177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20767b912bb1'
down_revision = '454f3680cbb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('sale_start', sa.DateTime(), nullable=True),
    sa.Column('sale_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_ticket_types_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_types'))
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticket_type_id', sa.Integer(), nullable=False),
    sa.Column('ticket_code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('purchased_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], name=op.f('fk_tickets_ticket_type_id_ticket_types')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tickets_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets')),
    sa.UniqueConstraint('ticket_code', name=op.f('uq_tickets_ticket_code'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_table('ticket_types')
    # ### end Alembic commands ###
